### ISSUE TITLE
Greenhouse Mk2 Water

### ISSUE THREAD

**Issue by RealTrueDeviL** [mrhid6/SF_Mod_FarmingMod#1]
Hi,

There's a fluid input on the greenhouse Mk2, but it does not seem to take water directly? It's looking for some form of canister, but I see no way to make the canister?

What am I missing?

Thanks

**Comment by mrhid6** [comment]
What recipe are you trying? It should take water directly from the water extractor ?

**Comment by RealTrueDeviL** [comment]
I trying to do the 5x wheat, it says 4x seed & water, I've plumbed the water directly from the water pump, but it's not working, it's showing a pic of some canister.. Lemme double check..
![SF-Water-Bug-1](https://user-images.githubusercontent.com/21058263/78504930-ef660980-7767-11ea-9aa4-9df649c16ea5.jpg)
![SF-Water-Bug-2](https://user-images.githubusercontent.com/21058263/78504934-f3922700-7767-11ea-93ff-2e639454ee96.jpg)

**Comment by RealTrueDeviL** [comment]
Btw, it looks like ALL the recipe's that require water, have the same icon, maybe it's a larger issue int he files/configs

EDIT: I see, the canister represents 'water' as a whole.. However, it's still not going into the Greenhouse..

**Comment by RealTrueDeviL** [comment]
Ok Quick update: I tried making a recipe in a Refiner (Water + Resin = Plastic) and seems that water isn't going into there either, I'll check 2moro, to make sure it's still going into my Coal Generator's..

If not, then maybe a mod broke it somehow...

NOW FIXED!! (I had the pipe on the output >.<)

**Comment by mrhid6** [comment]
Can this issue now be closed then?

**Comment by RealTrueDeviL** [comment]
No, water still isn't going into the Greenhouse Mk2, I resolved the issue with the Refinery not working..

**Comment by mrhid6** [comment]
Please contact me on discord Mrhid6#2851

**Comment by mrhid6** [comment]
Needed pipeline pump to increase water flow. Issue resolved.
