### ISSUE TITLE
Potato Icon Needs Changed

### ISSUE THREAD

**Issue by Jayshua83** [mrhid6/SF_Mod_FarmingMod#10]
Would be nice to have the Potato icon be a Potato. And since you grow Potatoes from Potatoes and NOT from seeds!

**Comment by mrhid6** [comment]
It’s a sack of potatoes but the game scales so you can’t see them


https://github.com/mrhid6/SF_Mod_FarmingMod/blob/master/Images/Icon_Potato.png
