### ISSUE TITLE
Heavy CPU with Greenhouse MK2

### ISSUE THREAD

**Issue by execute0r** [mrhid6/SF_Mod_FarmingMod#12]
Hi there
I´ve recently made some progress with your awesome mod :) But after setting up 6 greenhouses MK2 I got serious performance issues. With all of them switched off I got ~45% CPU Load according to the task manager. When I put just one to the working state, the load rises to ~70%, if I put all on I get a constant 100% load.
This is repeatable whenever I want. Is there any advise what I can do ?
If you need any more Information, just tell me :)

I´m using:
CL125236 - SML V2.2.1
Farming Mod 2.0.6
MoarFactory 1.1.6
MoarDevice 1.0.2
Moar Assets 1.0.3
Jetpack Mk.2 0.0.1
ExoSuit 0.0.10
PUREX Reprocessing 0.1.0

Intel I7-7700k @ 4,6Ghz
DDR4 16GB 
Nvidia GeForce GTX1070X

**Comment by Dark-talon** [comment]
Same, I have 6700k @ 4.6 Ghz and having a few of these greenhouses set up absolutely destroys my cpu. After I move away from them, cpu usage returns to normal.

**Comment by mrhid6** [comment]
We are going to be overhaulling the mod soon so this may not get fixed until then
