### ISSUE TITLE
Want to contribute documentation to this really neat mod.

### ISSUE THREAD

**Issue by shlomi-harif** [mrhid6/SF_Mod_FarmingMod#13]
I'd be happy to edit your wiki to reflect the new buildings, and also to provide documentation at around the quality of the "official" Satisfactory Wiki.

**Comment by vinnyviking** [comment]
Thsa would realy help to understand the working of the mod.
there are alot of things that need additional explanation.
E.g. How do you get a Doggo in the pen?

I am a Technical writer from profession and can help converting texts to common english

**Comment by mrhid6** [comment]
We will be overhauling farming mod after the Refined Power update so i see no need to update the Wiki just yet

**Comment by shlomi-harif** [comment]
That's cool. When you do; my offer stands. Yours and Refined Power are my
favorite mods. Wouldn't it be great if Coffee Stain compensated y'all for
all the work you'be done?


Cheers,

Shlomi
