### ISSUE TITLE
Unable to produce Doggo Chow

### ISSUE THREAD

**Issue by Hichi** [mrhid6/SF_Mod_FarmingMod#14]
I'am unable to produce/create/manufacture "Doggo Chow".
When I press "X" and search for it i do find it, but there is no available recipe in the assembler or the craft bench.
![Doggo_Chow](https://user-images.githubusercontent.com/5693399/90642080-3c87db00-e232-11ea-9614-5b0b19956217.png)

I am using this "modpack": 
[https://drive.google.com/open?id=1fYmQg5c0SCGTEFcSGVWG-MP1Thsy7pZe](url)

Since i know little about programing, I don't know if this is a mod-issue or because I have 29 mods installed.

**Comment by mrhid6** [comment]
It’s in the cooker
