### ISSUE TITLE
Doggo farm output

### ISSUE THREAD

**Issue by Viper3489753489** [mrhid6/SF_Mod_FarmingMod#4]
Hi, I have encountered a crash issue on multiplayer

Description
When a player loads the Doggo Farm if something is connected via the input/output and multiplayer session crashes. 

Affects:
- All players but the host

Issue:
[2020.06.15-21.11.39:790][618]LogFactory: Warning: Build_DoggoItemCollector_C_0: Checking of factory connection components failed: Error: 'OutputConnection' is not a valid name for this factory connection, the proper name is '(Conveyor)Output{id}'

Full log file can be found here:
[FactoryGame.zip](https://github.com/mrhid6/SF_Mod_FarmingMod/files/4783081/FactoryGame.zip)

If you need any additional information let me know I'll be happy to help

**Comment by Antik20** [comment]
Same Problem here but only with the input.  Workaround is, everytime i want to feed the lizard doggos, every player disconnects, the host connects a belt and then destroys it. afterwards everyone can reconnect.

**Comment by mrhid6** [comment]
Issue fixed when v2.0.5 is released
