### ISSUE TITLE
Greenhouse Mk3 Only Able To Grow Wheat?

### ISSUE THREAD

**Issue by DizzyDJW** [mrhid6/SF_Mod_FarmingMod#6]
I tore down the entire Mk2 Greenhouse setup to upgrade, just to find out that the Mk3s are only able to grow wheat.
Could you please add the other recipes to the Mk3s, so that I don't have to tear everything back down, again...?

**Comment by zstinnett** [comment]
I also just experienced this as well, other than that. This mod has been pretty awesome so far!

**Comment by mrhid6** [comment]
we are going to be overhaulling the mod so may not get fixed until then

**Comment by zstinnett** [comment]
Awesome, I look forward to the overhaul!! Thank you for your work!

>
